server:
  port: 8082

spring:
  datasource:
    username: root
    password: xhy123456
    jdbc-url: jdbc:mysql://localhost:3306/sp_oauth2?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

